foreground         #82BB94
#background        #14181D  # This looks way better but not good for low contrast, high brightness walls
background         #141517
cursor             #B6AC9B 

active_tab_foreground     #14181D
active_tab_background     #82BB94
inactive_tab_foreground   #82BB94
inactive_tab_background   #14181D

active_border_color   #495364
inactive_border_color #82BB94
bell_border_color     #313148

color0       #14181D
color8       #2B2C33
color1       #B6AC9B
color9       #495364
color2       #578878
color10      #578878
color3       #2E303D
color11      #2E303D
color4       #464E49
color12      #464E49
color5       #4D6056
color13      #4D6056
color6       #537366
color14      #537366
color7       #82BB94
color15      #82BB94
