-- Window rules
-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/

-- Opacity rules
hl.window_rule({ match = { class = "firefox" },                          opacity = "0.90 0.90" })
hl.window_rule({ match = { class = "steam" },                            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "steamwebhelper" },                   opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "Spotify" },                          opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "Code" },                             opacity = "0.95 0.95" })
hl.window_rule({ match = { class = "code-url-handler" },                 opacity = "0.95 0.95" })
hl.window_rule({ match = { class = "kitty" },                            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "ghostty" },                          opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "org.kde.dolphin" },                  opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "org.kde.ark" },                      opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "nwg-look" },                         opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "qt5ct" },                            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "qt6ct" },                            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "kvantummanager" },                   opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "1password" },                        opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "Signal" },                           opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "com.github.rafostar.Clapper" },      opacity = "0.90 0.90" })
hl.window_rule({ match = { class = "com.github.tchx84.Flatseal" },       opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "hu.kramo.Cartridges" },              opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "com.obsproject.Studio" },            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "gnome-boxes" },                      opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "discord" },                          opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "WebCord" },                          opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "ArmCord" },                          opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "app.drey.Warp" },                    opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "net.davidotek.pupgui2" },            opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "yad" },                              opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "io.github.alainm23.planify" },       opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "io.gitlab.theevilskeleton.Upscaler" }, opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "com.github.unrud.VideoDownloader" }, opacity = "0.80 0.80" })
hl.window_rule({ match = { class = "pavucontrol" },                      opacity = "0.80 0.70" })
hl.window_rule({ match = { class = "blueman-manager" },                  opacity = "0.80 0.70" })
hl.window_rule({ match = { class = "nm-applet" },                        opacity = "0.80 0.70" })
hl.window_rule({ match = { class = "nm-connection-editor" },             opacity = "0.80 0.70" })
hl.window_rule({ match = { class = "org.kde.polkit-kde-authentication-agent-1" }, opacity = "0.80 0.70" })

-- Float rules
hl.window_rule({ match = { title = "Picture-in-Picture" },               float = true })
hl.window_rule({ match = { class = "vlc" },                              float = true })
hl.window_rule({ match = { class = "kvantummanager" },                   float = true })
hl.window_rule({ match = { class = "qt5ct" },                            float = true })
hl.window_rule({ match = { class = "qt6ct" },                            float = true })
hl.window_rule({ match = { class = "nwg-look" },                         float = true })
hl.window_rule({ match = { class = "org.kde.ark" },                      float = true })
hl.window_rule({ match = { class = "com.github.rafostar.Clapper" },      float = true })
hl.window_rule({ match = { class = "app.drey.Warp" },                    float = true })
hl.window_rule({ match = { class = "net.davidotek.pupgui2" },            float = true })
hl.window_rule({ match = { class = "yad" },                              float = true })
hl.window_rule({ match = { class = "eog" },                              float = true })
hl.window_rule({ match = { class = "io.github.alainm23.planify" },       float = true })
hl.window_rule({ match = { class = "io.gitlab.theevilskeleton.Upscaler" }, float = true })
hl.window_rule({ match = { class = "com.github.unrud.VideoDownloader" }, float = true })
hl.window_rule({ match = { class = "pavucontrol" },                      float = true })
hl.window_rule({ match = { class = "blueman-manager" },                  float = true })
hl.window_rule({ match = { class = "nm-applet" },                        float = true })
hl.window_rule({ match = { class = "nm-connection-editor" },             float = true })
hl.window_rule({ match = { class = "org.kde.polkit-kde-authentication-agent-1" }, float = true })

-- Focus rules
hl.window_rule({ match = { class = "1Password" }, stay_focused = true })
